stages:
  - deploy

before_script:
  # Install Node.js and npm
  - curl -sL https://deb.nodesource.com/setup_20.x | bash -
  - apt-get install -y nodejs
  # Install Firebase tools
  - npm install -g firebase-tools

# Staging deployment
deploy_staging:
  stage: deploy
  only:
    - staging
  script:
    # Decode the staging service account key from Base64 and write to a file
    # Authenticate with Firebase
    - npm install
    - export FIREBASE_TOKEN=$FIREBASE_TOKEN
    - firebase use --add catchatapp-6f11c
    # Deploy Firebase functions with secrets using GitLab variables
    # Export environment variables
    - |
      echo "NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY" > .env
      echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" >> .env
      echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID" >> .env
      echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" >> .env
      echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" >> .env
      echo "NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID" >> .env
      echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env

    - echo "Building next-app"
    - npm run build
    - firebase deploy --only hosting
  environment:
    name: staging
    url: https://staging-api.catchat.com

# Production deployment
deploy_production:
  stage: deploy
  only:
    - production
  script:
    # Decode the production service account key from Base64 and write to a file
    # Authenticate with Firebase
    - npm install
    - export FIREBASE_TOKEN=$FIREBASE_TOKEN
    - firebase use --add catchatapp-staging
      # Export environment variables
    - |
      echo "NEXT_PUBLIC_FIREBASE_API_KEY=$NEXT_PUBLIC_FIREBASE_API_KEY" > .env
      echo "NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN=$NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN" >> .env
      echo "NEXT_PUBLIC_FIREBASE_PROJECT_ID=$NEXT_PUBLIC_FIREBASE_PROJECT_ID" >> .env
      echo "NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET=$NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET" >> .env
      echo "NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID" >> .env
      echo "NEXT_PUBLIC_FIREBASE_APP_ID=$NEXT_PUBLIC_FIREBASE_APP_ID" >> .env
      echo "NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL" >> .env
    # Deploy Firebase functions with secrets using GitLab variables
    - echo "Building next-app"
    - npm run build
    - firebase deploy --only hosting
  environment:
    name: production
    url: https://api.catchat.com
